name: cd
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build registry.hub.docker.com/day8au/dev-ci
        uses: elgohr/Publish-Docker-Github-Action@2.19
        with:
          name: day8au/dev-ci
          tag_semver: true
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}