name: ci
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build --tag dev-ci:latest .
          docker history dev-ci:latest
