name: ci
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build --tag day8au/dev-ci .
          docker history day8au/dev-ci
